import {
    getVersion,
    logs,
    ops,
    errors,
    getOpName,
    getErrorName,
    getLogType,
    protoBuild,
    PDU,
    GetLogPDU,
    GetLogResponsePDU,
    FlushPDU,
    FlushResponsePDU,
    SetClusterVersionPDU,
    SetupResponsePDU,
    NoOpPDU,
    NoOpResponsePDU,
    PutPDU,
    PutResponsePDU,
    GetPDU,
    GetResponsePDU,
    DeletePDU,
    DeleteResponsePDU,
} from './lib/kinetic';

export default {
    getVersion: getVersion,
    logs: logs,
    ops: ops,
    errors: errors,
    getOpName: getOpName,
    getErrorName: getErrorName,
    getLogType: getLogType,
    protoBuild: protoBuild,
    PDU: PDU,
    GetLogPDU: GetLogPDU,
    GetLogResponsePDU: GetLogResponsePDU,
    FlushPDU: FlushPDU,
    FlushResponsePDU: FlushResponsePDU,
    SetClusterVersionPDU: SetClusterVersionPDU,
    SetupResponsePDU: SetupResponsePDU,
    NoOpPDU: NoOpPDU,
    NoOpResponsePDU: NoOpResponsePDU,
    PutPDU: PutPDU,
    PutResponsePDU: PutResponsePDU,
    GetPDU: GetPDU,
    GetResponsePDU: GetResponsePDU,
    DeletePDU: DeletePDU,
    DeleteResponsePDU: DeleteResponsePDU,
};
